/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTE0 (number 1), WINC_CHIPEN
  @{ */
#define BOARD_WINC_CHIPEN_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_WINC_CHIPEN_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_WINC_CHIPEN_PIN 0U     /*!<@brief PORTE pin index: 0 */
                                     /* @} */

/*! @name PORTE1 (number 2), WINC_MOSI
  @{ */
#define BOARD_WINC_MOSI_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_WINC_MOSI_PIN 1U     /*!<@brief PORTE pin index: 1 */
                                   /* @} */

/*! @name PORTE2 (number 3), WINC_SCK
  @{ */
#define BOARD_WINC_SCK_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_WINC_SCK_PIN 2U     /*!<@brief PORTE pin index: 2 */
                                  /* @} */

/*! @name PORTE3 (number 4), WINC_MISO
  @{ */
#define BOARD_WINC_MISO_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_WINC_MISO_PIN 3U     /*!<@brief PORTE pin index: 3 */
                                   /* @} */

/*! @name PORTE4 (number 5), WINC_CS
  @{ */
#define BOARD_WINC_CS_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_WINC_CS_PIN 4U     /*!<@brief PORTE pin index: 4 */
                                 /* @} */

/*! @name PORTE5 (number 6), WINC_RESET
  @{ */
#define BOARD_WINC_RESET_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_WINC_RESET_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_WINC_RESET_PIN 5U     /*!<@brief PORTE pin index: 5 */
                                    /* @} */

/*! @name PORTE6 (number 7), WINC_IRQ
  @{ */
#define BOARD_WINC_IRQ_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_WINC_IRQ_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_WINC_IRQ_PIN 6U     /*!<@brief PORTE pin index: 6 */
                                  /* @} */

/*! @name ADC0_DP1 (number 14), SENSOR_ANODE
  @{ */
/* @} */

/*! @name ADC0_DM1 (number 15), WIFI_ANODE
  @{ */
/* @} */

/*! @name ADC1_DP1 (number 16), POWER_ANODE
  @{ */
/* @} */

/*! @name ADC0_DM0 (number 19), TRIPPED_ANODE
  @{ */
/* @} */

/*! @name ADC0_DP3 (number 20), NGR_FLT_ANODE
  @{ */
/* @} */

/*! @name ADC0_DM3 (number 21), GND_FLT_ANODE
  @{ */
/* @} */

/*! @name ADC1_SE18 (number 26), ADC_24V
  @{ */
/* @} */

/*! @name ADC0_SE23 (number 27), ADC_3V3
  @{ */
/* @} */

/*! @name PORTB20 (number 66), EXTF_CS
  @{ */
#define BOARD_EXTF_CS_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_EXTF_CS_PIN 20U    /*!<@brief PORTB pin index: 20 */
                                 /* @} */

/*! @name PORTB21 (number 67), EXTF_SCK
  @{ */
#define BOARD_EXTF_SCK_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_EXTF_SCK_PIN 21U    /*!<@brief PORTB pin index: 21 */
                                  /* @} */

/*! @name PORTB22 (number 68), EXTF_MOSI
  @{ */
#define BOARD_EXTF_MOSI_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_EXTF_MOSI_PIN 22U    /*!<@brief PORTB pin index: 22 */
                                   /* @} */

/*! @name PORTB23 (number 69), EXTF_MISO
  @{ */
#define BOARD_EXTF_MISO_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_EXTF_MISO_PIN 23U    /*!<@brief PORTB pin index: 23 */
                                   /* @} */

/*! @name PORTC0 (number 70), RELAY_TRIP
  @{ */
#define BOARD_RELAY_TRIP_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_RELAY_TRIP_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_RELAY_TRIP_PIN 0U     /*!<@brief PORTC pin index: 0 */
                                    /* @} */

/*! @name PORTC1 (number 71), RELAY_NGR
  @{ */
#define BOARD_RELAY_NGR_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_RELAY_NGR_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_RELAY_NGR_PIN 1U     /*!<@brief PORTC pin index: 1 */
                                   /* @} */

/*! @name PORTC2 (number 72), RELAY_AUX
  @{ */
#define BOARD_RELAY_AUX_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_RELAY_AUX_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_RELAY_AUX_PIN 2U     /*!<@brief PORTC pin index: 2 */
                                   /* @} */

/*! @name PORTC4 (number 76), RELAY_GND
  @{ */
#define BOARD_RELAY_GND_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_RELAY_GND_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_RELAY_GND_PIN 4U     /*!<@brief PORTC pin index: 4 */
                                   /* @} */

/*! @name PORTC8 (number 80), WIFI_ENABLE
  @{ */
#define BOARD_WIFI_ENABLE_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_WIFI_ENABLE_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_WIFI_ENABLE_PIN 8U     /*!<@brief PORTC pin index: 8 */
                                     /* @} */

/*! @name PORTC9 (number 81), TEST_P
  @{ */
#define BOARD_TEST_P_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_TEST_P_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_TEST_P_PIN 9U     /*!<@brief PORTC pin index: 9 */
                                /* @} */

/*! @name PORTC10 (number 82), RESET_P
  @{ */
#define BOARD_RESET_P_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_RESET_P_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_RESET_P_PIN 10U    /*!<@brief PORTC pin index: 10 */
                                 /* @} */

/*! @name PORTC16 (number 90), HMI_RS485_RX
  @{ */
#define BOARD_HMI_RS485_RX_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_HMI_RS485_RX_PIN 16U    /*!<@brief PORTC pin index: 16 */
                                      /* @} */

/*! @name PORTC17 (number 91), HMI_RS485_TX
  @{ */
#define BOARD_HMI_RS485_TX_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_HMI_RS485_TX_PIN 17U    /*!<@brief PORTC pin index: 17 */
                                      /* @} */

/*! @name PORTC18 (number 92), HMI_RS485_DIR
  @{ */
#define BOARD_HMI_RS485_DIR_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_HMI_RS485_DIR_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_HMI_RS485_DIR_PIN 18U    /*!<@brief PORTC pin index: 18 */
                                       /* @} */

/*! @name PORTD2 (number 95), SENSOR_RS485_RX
  @{ */
#define BOARD_SENSOR_RS485_RX_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_SENSOR_RS485_RX_PIN 2U     /*!<@brief PORTD pin index: 2 */
                                         /* @} */

/*! @name PORTD3 (number 96), SENSOR_RS485_TX
  @{ */
#define BOARD_SENSOR_RS485_TX_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_SENSOR_RS485_TX_PIN 3U     /*!<@brief PORTD pin index: 3 */
                                         /* @} */

/*! @name PORTD0 (number 93), SENSOR_RS485_DIR
  @{ */
#define BOARD_SENSOR_RS485_DIR_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_SENSOR_RS485_DIR_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_SENSOR_RS485_DIR_PIN 0U     /*!<@brief PORTD pin index: 0 */
                                          /* @} */

/*! @name PORTD4 (number 97), POWER_LED
  @{ */
#define BOARD_POWER_LED_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_POWER_LED_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_POWER_LED_PIN 4U     /*!<@brief PORTD pin index: 4 */
                                   /* @} */

/*! @name PORTD5 (number 98), WIFI_LED
  @{ */
#define BOARD_WIFI_LED_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_WIFI_LED_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_WIFI_LED_PIN 5U     /*!<@brief PORTD pin index: 5 */
                                  /* @} */

/*! @name PORTD6 (number 99), SENSOR_LED
  @{ */
#define BOARD_SENSOR_LED_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_SENSOR_LED_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_SENSOR_LED_PIN 6U     /*!<@brief PORTD pin index: 6 */
                                    /* @} */

/*! @name PORTC6 (number 78), NGR_FLT_LED
  @{ */
#define BOARD_NGR_FLT_LED_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_NGR_FLT_LED_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_NGR_FLT_LED_PIN 6U     /*!<@brief PORTC pin index: 6 */
                                     /* @} */

/*! @name PORTC7 (number 79), GND_FLT_LED
  @{ */
#define BOARD_GND_FLT_LED_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_GND_FLT_LED_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_GND_FLT_LED_PIN 7U     /*!<@brief PORTC pin index: 7 */
                                     /* @} */

/*! @name PORTC5 (number 77), TRIPPED_LED
  @{ */
#define BOARD_TRIPPED_LED_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_TRIPPED_LED_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_TRIPPED_LED_PIN 5U     /*!<@brief PORTC pin index: 5 */
                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*! @name PORTC6 (number 78), NGR_FLT_LED
  @{ */
#define BOARD_SW2_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_SW2_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_SW2_PIN 6U     /*!<@brief PORTC pin index: 6 */
                             /* @} */

/*! @name PORTA4 (number 38), SW3
  @{ */
#define BOARD_SW3_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_SW3_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_SW3_PIN 4U     /*!<@brief PORTA pin index: 4 */
                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitButtonsPins(void);

/*! @name PORTB21 (number 67), EXTF_SCK
  @{ */
#define BOARD_LED_BLUE_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_LED_BLUE_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_LED_BLUE_PIN 21U    /*!<@brief PORTB pin index: 21 */
                                  /* @} */

/*! @name PORTB22 (number 68), EXTF_MOSI
  @{ */
#define BOARD_LED_RED_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_LED_RED_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_LED_RED_PIN 22U    /*!<@brief PORTB pin index: 22 */
                                 /* @} */

/*! @name PORTE26 (number 33), J2[1]/D12[4]/LEDRGB_GREEN
  @{ */
#define BOARD_LED_GREEN_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_LED_GREEN_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_LED_GREEN_PIN 26U    /*!<@brief PORTE pin index: 26 */
                                   /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*! @name PORTB17 (number 63), U10[1]/UART0_TX
  @{ */
#define BOARD_DEBUG_UART_TX_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_DEBUG_UART_TX_PIN 17U    /*!<@brief PORTB pin index: 17 */
                                       /* @} */

/*! @name PORTB16 (number 62), U7[4]/UART0_RX
  @{ */
#define BOARD_DEBUG_UART_RX_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_DEBUG_UART_RX_PIN 16U    /*!<@brief PORTB pin index: 16 */
                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/*! @name PORTA18 (number 50), U13[16]/RMII_RXCLK
  @{ */
#define BOARD_EXTAL0_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_EXTAL0_PIN 18U    /*!<@brief PORTA pin index: 18 */
                                /* @} */

/*! @name EXTAL32 (number 29), Y3[2]/EXTAL32_RTC
  @{ */
/* @} */

/*! @name XTAL32 (number 28), Y3[1]/XTAL32_RTC
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitOSCPins(void);

/*! @name PORTE25 (number 32), J2[18]/U8[6]/I2C0_SDA
  @{ */
#define BOARD_ACCEL_SDA_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_ACCEL_SDA_PIN 25U    /*!<@brief PORTE pin index: 25 */
                                   /* @} */

/*! @name PORTE24 (number 31), J2[20]/U8[4]/I2C0_SCL
  @{ */
#define BOARD_ACCEL_SCL_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_ACCEL_SCL_PIN 24U    /*!<@brief PORTE pin index: 24 */
                                   /* @} */

/*! @name PORTC6 (number 78), NGR_FLT_LED
  @{ */
#define BOARD_ACCEL_INT1_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_ACCEL_INT1_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_ACCEL_INT1_PIN 6U     /*!<@brief PORTC pin index: 6 */
                                    /* @} */

/*! @name PORTC13 (number 85), U8[9]
  @{ */
#define BOARD_ACCEL_INT2_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_ACCEL_INT2_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_ACCEL_INT2_PIN 13U    /*!<@brief PORTC pin index: 13 */
                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitACCELPins(void);

#define SOPT2_RMIISRC_EXTAL 0x00u /*!<@brief RMII clock source select: EXTAL clock */

/*! @name PORTB1 (number 54), U13[11]/RMII0_MDC
  @{ */
#define BOARD_RMII0_MDC_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_RMII0_MDC_PIN 1U     /*!<@brief PORTB pin index: 1 */
                                   /* @} */

/*! @name PORTB0 (number 53), U13[10]/RMII0_MDIO
  @{ */
#define BOARD_RMII0_MDIO_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_RMII0_MDIO_PIN 0U     /*!<@brief PORTB pin index: 0 */
                                    /* @} */

/*! @name PORTA13 (number 43), U13[13]/RMII0_RXD_0
  @{ */
#define BOARD_RMII0_RXD0_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_RMII0_RXD0_PIN 13U    /*!<@brief PORTA pin index: 13 */
                                    /* @} */

/*! @name PORTA12 (number 42), U13[12]/RMII0_RXD_1
  @{ */
#define BOARD_RMII0_RXD1_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_RMII0_RXD1_PIN 12U    /*!<@brief PORTA pin index: 12 */
                                    /* @} */

/*! @name PORTA5 (number 39), U13[17]/RMII0_RXER
  @{ */
#define BOARD_RMII0_RXER_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_RMII0_RXER_PIN 5U     /*!<@brief PORTA pin index: 5 */
                                    /* @} */

/*! @name PORTA16 (number 46), U13[20]/RMII0_TXD0
  @{ */
#define BOARD_RMII0_TXD0_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_RMII0_TXD0_PIN 16U    /*!<@brief PORTA pin index: 16 */
                                    /* @} */

/*! @name PORTA17 (number 47), U13[21]/RMII0_TXD1
  @{ */
#define BOARD_RMII0_TXD1_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_RMII0_TXD1_PIN 17U    /*!<@brief PORTA pin index: 17 */
                                    /* @} */

/*! @name PORTA15 (number 45), U13[19]/RMII0_TXEN
  @{ */
#define BOARD_RMII0_TXEN_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_RMII0_TXEN_PIN 15U    /*!<@brief PORTA pin index: 15 */
                                    /* @} */

/*! @name PORTA14 (number 44), U13[15]/RMII0_CRS_DV
  @{ */
#define BOARD_RMII0_CRS_DV_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_RMII0_CRS_DV_PIN 14U    /*!<@brief PORTA pin index: 14 */
                                      /* @} */

/*! @name PORTA18 (number 50), U13[16]/RMII_RXCLK
  @{ */
#define BOARD_RMII_RXCLK_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_RMII_RXCLK_PIN 18U    /*!<@brief PORTA pin index: 18 */
                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitENETPins(void);

/*! @name PORTE0 (number 1), WINC_CHIPEN
  @{ */
#define BOARD_SDHC0_D1_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_SDHC0_D1_PIN 0U     /*!<@brief PORTE pin index: 0 */
                                  /* @} */

/*! @name PORTE1 (number 2), WINC_MOSI
  @{ */
#define BOARD_SDHC0_D0_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_SDHC0_D0_PIN 1U     /*!<@brief PORTE pin index: 1 */
                                  /* @} */

/*! @name PORTE2 (number 3), WINC_SCK
  @{ */
#define BOARD_SDHC0_DCLK_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_SDHC0_DCLK_PIN 2U     /*!<@brief PORTE pin index: 2 */
                                    /* @} */

/*! @name PORTE3 (number 4), WINC_MISO
  @{ */
#define BOARD_SDHC0_CMD_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_SDHC0_CMD_PIN 3U     /*!<@brief PORTE pin index: 3 */
                                   /* @} */

/*! @name PORTE4 (number 5), WINC_CS
  @{ */
#define BOARD_SDHC0_D3_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_SDHC0_D3_PIN 4U     /*!<@brief PORTE pin index: 4 */
                                  /* @} */

/*! @name PORTE5 (number 6), WINC_RESET
  @{ */
#define BOARD_SDHC0_D2_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_SDHC0_D2_PIN 5U     /*!<@brief PORTE pin index: 5 */
                                  /* @} */

/*! @name PORTE6 (number 7), WINC_IRQ
  @{ */
#define BOARD_SDHC_CD_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_SDHC_CD_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_SDHC_CD_PIN 6U     /*!<@brief PORTE pin index: 6 */
                                 /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSDHCPins(void);

/*! @name USB0_DP (number 10), J22[3]/K64_MICRO_USB_DP
  @{ */
/* @} */

/*! @name USB0_DM (number 11), J22[2]/K64_MICRO_USB_DN
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUSBPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
